# can find and replace cursor with code if using VSCode
cursor --install-extension anysphere.cursorpyright
cursor --install-extension bierner.lit-html
cursor --install-extension bierner.markdown-mermaid
cursor --install-extension cduruk.thrift
cursor --install-extension charliermarsh.ruff
cursor --install-extension dbaeumer.vscode-eslint
cursor --install-extension docker.docker
cursor --install-extension eamodio.gitlens
cursor --install-extension editorconfig.editorconfig
cursor --install-extension esbenp.prettier-vscode
cursor --install-extension golang.go
cursor --install-extension graphql.vscode-graphql
cursor --install-extension graphql.vscode-graphql-syntax
cursor --install-extension hashicorp.hcl
cursor --install-extension hashicorp.terraform
cursor --install-extension jeremyrajan.webpack
cursor --install-extension mikestead.dotenv
cursor --install-extension ms-azuretools.vscode-docker
cursor --install-extension ms-playwright.playwright
cursor --install-extension ms-python.debugpy
cursor --install-extension ms-python.flake8
cursor --install-extension ms-python.isort
cursor --install-extension ms-python.mypy-type-checker
cursor --install-extension ms-python.pylint
cursor --install-extension ms-python.python
cursor --install-extension ms-python.vscode-pylance
cursor --install-extension ms-toolsai.jupyter
cursor --install-extension ms-toolsai.jupyter-keymap
cursor --install-extension ms-toolsai.jupyter-renderers
cursor --install-extension ms-toolsai.vscode-jupyter-cell-tags
cursor --install-extension ms-toolsai.vscode-jupyter-slideshow
cursor --install-extension ms-vscode.makefile-tools
cursor --install-extension orsenkucher.vscode-graphql
cursor --install-extension pjmiravalle.terraform-advanced-syntax-highlighting
cursor --install-extension redhat.vscode-yaml
cursor --install-extension runem.lit-plugin
cursor --install-extension stackbuild.bazel-stack-vscode
cursor --install-extension tchoupinax.tilt
cursor --install-extension tilt-dev.tiltfile
cursor --install-extension visualstudioexptteam.intellicode-api-usage-examples
cursor --install-extension visualstudioexptteam.vscodeintellicode
cursor --install-extension yoavbls.pretty-ts-errors
cursor --install-extension yzhang.markdown-all-in-one
cursor --install-extension zxh404.vscode-proto3